
const GET_SELLER="GET_SELLER"
const SHOW_DETAIL="SHOW_DETAIL"
const HIDE_DETAIL="HIDE_DETAIL"
const GET_GOODS='GET_GOODS'

export default {
	GET_SELLER,
	SHOW_DETAIL,
	HIDE_DETAIL,
	GET_GOODS
}